// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfsCZLyfBBN7a1uLoJGewM5C98iEA_dIk',
    appId: '1:807903558584:web:ac78e1252e2322f031ed4d',
    messagingSenderId: '807903558584',
    projectId: 'zoho-clone-6cccf',
    authDomain: 'zoho-clone-6cccf.firebaseapp.com',
    storageBucket: 'zoho-clone-6cccf.firebasestorage.app',
    measurementId: 'G-HRMXVDC4FZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIdXzvcRR37UGtJ3pzfvXVvKkoqv5Smpw',
    appId: '1:807903558584:android:533bcff0de70610831ed4d',
    messagingSenderId: '807903558584',
    projectId: 'zoho-clone-6cccf',
    storageBucket: 'zoho-clone-6cccf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP_JFOL-xQRAOChsFTuMg6gw1HDo0aqNY',
    appId: '1:807903558584:ios:a900e2283f21996b31ed4d',
    messagingSenderId: '807903558584',
    projectId: 'zoho-clone-6cccf',
    storageBucket: 'zoho-clone-6cccf.firebasestorage.app',
    iosBundleId: 'com.example.zohoClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP_JFOL-xQRAOChsFTuMg6gw1HDo0aqNY',
    appId: '1:807903558584:ios:a900e2283f21996b31ed4d',
    messagingSenderId: '807903558584',
    projectId: 'zoho-clone-6cccf',
    storageBucket: 'zoho-clone-6cccf.firebasestorage.app',
    iosBundleId: 'com.example.zohoClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfsCZLyfBBN7a1uLoJGewM5C98iEA_dIk',
    appId: '1:807903558584:web:f0a758610693a12931ed4d',
    messagingSenderId: '807903558584',
    projectId: 'zoho-clone-6cccf',
    authDomain: 'zoho-clone-6cccf.firebaseapp.com',
    storageBucket: 'zoho-clone-6cccf.firebasestorage.app',
    measurementId: 'G-GTC41H78W4',
  );
}
